### PR TITLE
Added Redux and auth

### PR DESCRIPTION
**Pull request by spraveenofficial**
Added React-Redux.
Added Login and Signup with OTP.
Added Auth Actions.
Added Auth Constants.

### CODE REVIEW

**Review by KanekarSnehal — COMMENTED** [review]
Good use of regex
UI looks great

**Review by Richa-rani02 — APPROVED** [review]
Code looks good
Liked Otp authentication part

**Comment by Richa-rani02** [comment]
preview link is not working u can check that

**Comment by spraveenofficial** [comment]
> preview link is not working u can check that

Yes, only singup & login pages are there. You can check login and signup route.

**Pull request merged**
